version: '2'

services:

  app:
    build: app
    privileged: true
    network_mode: host
    volumes:
      - /dev/bus/usb:/dev/bus/usb
      - ./app:/app
      # - /tmp/.X11-unix:/tmp/.X11-unix
      # - /home/$USER/.android:/root/.android
    ports:
      - 8081:8081

  mock:
    build: mock
    volumes:
      - ./mock:/mock
    ports:
      - 80:80
